### ISSUE TITLE
Single service collection/IHost for multiple tests

### ISSUE THREAD

**Issue by markm77** [martincostello/xunit-logging#156]
Hi there,

Thanks for this library - v. helpful. However I need to share a single .NET host and service collection between multiple Xunit tests and am struggling to do this whilst capturing log output separately for each test via iLogger.

You can see more about my scenario here: https://github.com/dotnet/extensions/issues/3259. (A small change is that I now need to share a .NET Host (web host) rather than .NET Generic Host.)

Is there a way to tag each DI scope with the test being performed and then somehow use that to route iLogger logging to the correct test log?

BR,
Mark

**Comment by martincostello** [comment]
Hi @markm77  - thanks for your question.

This _should_ be supported out-of-the-box (at least, the infrastructure for it).

You can see how this is set up in the [integration tests](https://github.com/martincostello/xunit-logging/blob/main/tests/Logging.XUnit.Tests/Integration/HttpApplicationTests.cs) where there's a sample MVC application that is wired-up to the xunit `ITestOutputHelper` of each test via the [`ITestOutputHelperAccessor`](https://github.com/martincostello/xunit-logging/blob/b4cabcd6c66f49f2d312c3117cdd5b2bf6458a92/src/Logging.XUnit/ITestOutputHelperAccessor.cs#L11) interface.

If instead of passing the `ITestOutputHelper` to [`AddXUnit(ITestOutputHelper)`](https://github.com/martincostello/xunit-logging/blob/6ec5d0b31c45708334a10e4632063f0c732df9e4/src/Logging.XUnit/XUnitLoggerExtensions.cs#L117) directly, instead if you pass it an `ITestOutputHelperAccessor` (there's [another overload `AddXUnit(ITestOutputHelperAccessor)`](https://github.com/martincostello/xunit-logging/blob/6ec5d0b31c45708334a10e4632063f0c732df9e4/src/Logging.XUnit/XUnitLoggerExtensions.cs#L49)) and implement that on a fixture, you should be able to associate the active `ITestOutputHelper` with it per test have have the logs routed appropriately, and then remove it at the end of the test.

We use this pattern extensively at my work for our ASP.NET Core applications' xunit integration test suites, and there's some open source examples of using this approach in some other test suites I maintain here:

  * [martincostello/alexa-london-travel-site](https://github.com/martincostello/alexa-london-travel-site/blob/b6989da53ee39c39ab66eb2387df4593bbd7ae86/tests/LondonTravel.Site.Tests/Integration/TestServerFixture.cs#L81)
  * [aspnet-contrib/AspNet.Security.OAuth.Providers](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/800255de0e076422d017d2e37bef63a1e0cd7f03/test/AspNet.Security.OAuth.Providers.Tests/Infrastructure/ApplicationFactory.cs#L61)

In our case, we use a base class for all our integration tests to reduce as much of the boilerplate as possible, leaving each test class to just need to inherit from the base class and have an `ITestOutputHelper` and fixture parameter to pass to the base class' constructor to wire things up.

An alternative approach you could use is to just use `AddXUnit()`, and resolve the default `ITestOutputHelperAccessor` from your `TestServer`'s `IServiceCollection` before you start an HTTP request, and set the logger there manually in some way. The default implementation is backed by an `AsyncLocal` similar to David Fowler's suggestion in the linked issue.

https://github.com/martincostello/xunit-logging/blob/6ec5d0b31c45708334a10e4632063f0c732df9e4/src/Logging.XUnit/AmbientTestOutputHelperAccessor.cs#L18

Hope this helps!

## Worked Example

The tests use a shared HTTP server fixture using [`WebApplicationFactory<T>`](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.1#basic-tests-with-the-default-webapplicationfactory) implements `ITestOutputHelperAccessor`:

https://github.com/martincostello/xunit-logging/blob/b4cabcd6c66f49f2d312c3117cdd5b2bf6458a92/tests/Logging.XUnit.Tests/Integration/HttpServerFixture.cs#L15

https://github.com/martincostello/xunit-logging/blob/b4cabcd6c66f49f2d312c3117cdd5b2bf6458a92/tests/Logging.XUnit.Tests/Integration/HttpServerFixture.cs#L26

Then it registers itself as the xunit logger:

https://github.com/martincostello/xunit-logging/blob/b4cabcd6c66f49f2d312c3117cdd5b2bf6458a92/tests/Logging.XUnit.Tests/Integration/HttpServerFixture.cs#L31

The tests then set the `ITestOutputHelper` passed into their constructor against the fixture associated with the server:

https://github.com/martincostello/xunit-logging/blob/b4cabcd6c66f49f2d312c3117cdd5b2bf6458a92/tests/Logging.XUnit.Tests/Integration/HttpApplicationTests.cs#L21

The tests also implement `IDisposable` so that xunit tidies up the output helper afterwards:

https://github.com/martincostello/xunit-logging/blob/b4cabcd6c66f49f2d312c3117cdd5b2bf6458a92/tests/Logging.XUnit.Tests/Integration/HttpApplicationTests.cs#L26-L29

**Comment by markm77** [comment]
Hi Martin,

Thanks very much for the detailed response, appreciated!

I cloned Logging.Xunit and looked at your integration test example in more detail.

A question: does the ```ITestOutputHelperAccessor``` fixture approach allow running tests in parallel? I'm thinking it doesn't because the ```OutputHelper``` gets changed at the start of each test but I may be missing something. I have integration tests which connect with (and test) third-party systems including sometimes waiting a while for things. So running tests in parallel is a must.

But maybe your second suggestion contains the answer. I need to learn more about ```AsyncLocal``` but is the idea of ```AmbientTestOutputHelperAccessor``` that I could set ```OutputHelper``` at the start of an async Xunit test and then all code called in that test (including awaited code) would have logging routed to that ```OutputHelper```? Would that allow parallel running of tests with correct log routing? Would things be okay when something external to the test (e.g. singleton service independent action) tries to log and there is no available ```OutputHelper```?

BR,
Mark

PS: Just to note I had to hand-edit project files in Logging.Xunit to build the top-level solution due to Nuget Package issues. Wouldn't build out of the box in either VS or Rider. Just FYI.

**Comment by martincostello** [comment]
> A question: does the `ITestOutputHelperAccessor` fixture approach allow running tests in parallel? I'm thinking it doesn't because the `OutputHelper` gets changed at the start of each test but I may be missing something. I have integration tests which connect with (and test) third-party systems including sometimes waiting a while for things. So running tests in parallel is a must.

I don't think it does no as the fixture is shared amongst all the tests, at least not by default. However if you used an `AsyncLocal<ITestOutputHelper>` to back the property of the accessor in your fixture, then it _might_ work as long as the thread running the xunit constructor for a test is the same thread running the test method. I haven't tried this out myself, but it's worth you exploring to see if that small adjustment to the fixture _"just works"_.

> But maybe your second suggestion contains the answer. I need to learn more about `AsyncLocal` but is the idea of `AmbientTestOutputHelperAccessor` that I could set `OutputHelper` at the start of an async Xunit test and then all code called in that test (including awaited code) would have logging routed to that `OutputHelper`? Would that allow parallel running of tests with correct log routing?

If you're using `TestServer` (where the test method thread just calls into the implementation of your service on the same thread), then an `AsyncLocal<T>` should resolve the same code both in the test method (to set) and in the application (to get). This approach wouldn't work if you host the application on a real port in Kestrel as then it would be doing IPC so the threads wouldn't be the same (for example, this wouldn't work with the Selenium UI tests in my alexa-london-travel-site project I linked to above).

> Would things be okay when something external to the test (e.g. singleton service independent action) tries to log and there is no available `OutputHelper`?

Yes, if there's no `ITestOutputHelper` available then the logger becomes a no-op.

https://github.com/martincostello/xunit-logging/blob/b4cabcd6c66f49f2d312c3117cdd5b2bf6458a92/src/Logging.XUnit/XUnitLogger.cs#L160-L165

> PS: Just to note I had to hand-edit project files in Logging.Xunit to build the top-level solution due to Nuget Package issues. Wouldn't build out of the box in either VS or Rider. Just FYI.

I'm going to guess this is from the recent changes from #151 to use the new central NuGet package management functionality. It might just be that you're not using the latest version of Visual Studio that understands the new `Directory.Packages.Props` file. I don't think Rider supports it yet either. If you run `dotnet restore` from a terminal in the root directory and tell Rider to not try and restore missing packages then it should work fine without needing to tweak things.

**Comment by markm77** [comment]
Thanks Martin. I did implement a version of your ```AsyncLocal<ITestOutputHelper>``` suggestion. But then when going to test discovered with my latest design Xunit won't run tests in parallel anyway which is very annoying! However I will keep with this approach in the hope Xunit update parallelism options with v3. I got around the issue of constructor vs test method by calling a method to set ```OutputHelper``` at the start of each test method.

> I'm going to guess this is from the recent changes from #151 to use the new central NuGet package management functionality.

Seems ```dotnet build``` and ```dotnet restore``` work out of the box but not ```dotnet test```. I was using VS 16.6.5 (latest before today).

Seems issue is with analyzers. I had to e.g. modify SampleApp.csproj as follows (which I'm not sure is correct):
```xaml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);CA1801;CA1822;SA1600</NoWarn>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Update="coverlet.msbuild" Version="2.9.0" />
    <PackageReference Update="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="3.0.0" />
    <PackageReference Update="StyleCop.Analyzers" Version="1.1.118" />
    <PackageReference Update="Microsoft.SourceLink.GitHub" Version="1.0.0" />
    <PackageReference Update="ReportGenerator" Version="4.6.4" />
  </ItemGroup>
</Project>
```

Happy to run any specific test if you want help with this.

**Comment by markm77** [comment]
PS Feel free to close issue as from my side it's resolved thanks to your help!

**Comment by martincostello** [comment]
Glad you got everything functionally working (even if the parallelism doesn't)!

**Comment by martincostello** [comment]
FYI, when I get some time this week I'm going to update the docs and sample to cover this scenario 😃

**Comment by markm77** [comment]
Sounds great. I'm actually modifying my code to support both fixture property backing types, ```AsyncLocal<ITestOutputHelper>``` and plain ```ITestOutputHelper```, since the latter is better in serial testing as captures more e.g. logging from external HTTP re-direct back to fixture web host. In future I hope to have a switch for parallel or serial testing which would also configure this.
